2018-07-06 14:04:24.635 [error] <0.307.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.312.0> exit with reason normal in context child_terminated
2018-07-06 14:04:24.679 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 14:04:24.688 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 14:04:24.694 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 14:04:24.697 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 14:04:24.699 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 14:04:24.699 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 14:04:24.714 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 14:04:24.714 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 14:04:24.716 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 14:04:24.716 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 14:04:24.716 [info] <0.33.0> Application awe started on node nonode@nohost
2018-07-06 14:05:59.827 [error] <0.299.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.304.0> exit with reason normal in context child_terminated
2018-07-06 14:05:59.874 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 14:05:59.883 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 14:05:59.891 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 14:05:59.895 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 14:05:59.897 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 14:05:59.897 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 14:05:59.908 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 14:05:59.908 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 14:05:59.910 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 14:05:59.910 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 14:05:59.912 [error] <0.375.0>@Elixir.Plug.Adapters.Cowboy2:child_spec CRASH REPORT Process <0.375.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Plug.Adapters.Cowboy2':child_spec(http, 'Elixir.AgalaWebhooksExamples.Router', [], [{port,8080}]) in application_master:init/4 line 134
2018-07-06 14:05:59.938 [info] <0.33.0>@Elixir.Plug.Adapters.Cowboy2:child_spec Application awe exited with reason: call to undefined function 'Elixir.Plug.Adapters.Cowboy2':child_spec(http, 'Elixir.AgalaWebhooksExamples.Router', [], [{port,8080}])
2018-07-06 14:07:26.425 [error] <0.260.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.265.0> exit with reason normal in context child_terminated
2018-07-06 14:07:26.489 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 14:07:26.505 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 14:07:26.531 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 14:07:26.548 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 14:07:26.565 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 14:07:26.565 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 14:07:26.589 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 14:07:26.589 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 14:07:26.602 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 14:07:26.602 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 14:07:27.318 [warning] <0.32.0> lager_error_logger_h dropped 68 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-06 14:09:22.839 [error] <0.259.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.264.0> exit with reason normal in context child_terminated
2018-07-06 14:09:22.880 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 14:09:22.886 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 14:09:22.890 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 14:09:22.892 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 14:09:22.894 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 14:09:22.894 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 14:09:22.902 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 14:09:22.902 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 14:09:22.904 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 14:09:22.904 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 14:09:23.109 [warning] <0.32.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-06 14:12:03.319 [error] <0.278.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.283.0> exit with reason normal in context child_terminated
2018-07-06 14:12:03.360 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 14:12:03.368 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 14:12:03.373 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 14:12:03.376 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 14:12:03.378 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 14:12:03.378 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 14:12:03.387 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 14:12:03.387 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 14:12:03.389 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 14:12:03.389 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 14:12:04.120 [warning] <0.32.0> lager_error_logger_h dropped 68 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-06 19:07:25.128 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"br...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:07:25.183 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.541.0>,1,<0.542.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtm...">>,...},...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:07:26.183 [error] <0.545.0> CRASH REPORT Process <0.545.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"br, gzip, deflate">>,<<"accept-language">> => <<"en-us">>,<<"...">> => ...,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:07:26.184 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.544.0>,1,<0.545.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encod...">> => ...,...},...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:16.456 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:16.457 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.554.0>,1,<0.555.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:16.646 [error] <0.558.0> CRASH REPORT Process <0.558.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:16.648 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.557.0>,1,<0.558.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:16.881 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:16.883 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.560.0>,1,<0.561.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:17.340 [error] <0.564.0> CRASH REPORT Process <0.564.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:17.342 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.563.0>,1,<0.564.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:18.021 [error] <0.567.0> CRASH REPORT Process <0.567.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:18.023 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.566.0>,1,<0.567.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:19.145 [error] <0.570.0> CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:19.146 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.569.0>,1,<0.570.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:22.627 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:22.629 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.572.0>,1,<0.573.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:40.751 [error] <0.576.0> CRASH REPORT Process <0.576.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:40.753 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.575.0>,1,<0.576.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:13:01.687 [error] <0.631.0> CRASH REPORT Process <0.631.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:13:01.687 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.630.0>,1,<0.631.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:13:46.092 [error] <0.634.0> CRASH REPORT Process <0.634.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"connection">> => <<"close">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:13:46.095 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.633.0>,1,<0.634.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:14:09.506 [error] <0.286.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.291.0> exit with reason normal in context child_terminated
2018-07-06 19:14:09.549 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 19:14:09.557 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 19:14:09.560 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 19:14:09.562 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 19:14:09.564 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 19:14:09.564 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 19:14:09.573 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 19:14:09.573 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 19:14:09.577 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 19:14:09.577 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 19:14:10.111 [warning] <0.32.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-06 19:14:17.181 [error] <0.472.0> CRASH REPORT Process <0.472.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:14:17.236 [error] <0.338.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.471.0>,1,<0.472.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:14:21.625 [error] <0.475.0> CRASH REPORT Process <0.475.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"connection">> => <<"close">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:14:21.632 [error] <0.338.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.474.0>,1,<0.475.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:14:28.462 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"connection">> => <<"close">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:14:28.464 [error] <0.338.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.477.0>,1,<0.478.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:14:59.464 [error] <0.273.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.278.0> exit with reason normal in context child_terminated
2018-07-06 19:14:59.514 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 19:14:59.520 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 19:14:59.524 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 19:14:59.526 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 19:14:59.528 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 19:14:59.528 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 19:14:59.539 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 19:14:59.539 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 19:14:59.542 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 19:14:59.543 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 19:15:00.113 [warning] <0.32.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-06 19:16:23.537 [error] <0.251.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.256.0> exit with reason normal in context child_terminated
2018-07-06 19:16:23.581 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 19:16:23.589 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 19:16:23.593 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 19:16:23.595 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 19:16:23.597 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 19:16:23.597 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 19:16:23.608 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 19:16:23.608 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 19:16:23.612 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 19:16:23.612 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 19:16:24.119 [warning] <0.32.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-06 19:16:48.988 [error] <0.440.0> CRASH REPORT Process <0.440.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:8080">>,<<"user-agent">> => <<"curl/7.54.0">>},host => <<"localh...">>,...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:16:49.031 [error] <0.303.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.439.0>,1,<0.440.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"lo...">>,...},...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:19:21.846 [error] <0.251.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.256.0> exit with reason normal in context child_terminated
2018-07-06 19:19:21.892 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 19:19:21.900 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 19:19:21.903 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 19:19:21.905 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 19:19:21.907 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 19:19:21.907 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 19:19:21.915 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 19:19:21.915 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 19:19:21.919 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 19:19:21.919 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 19:19:22.117 [warning] <0.32.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-06 19:20:28.845 [error] <0.251.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.256.0> exit with reason normal in context child_terminated
2018-07-06 19:20:28.891 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 19:20:28.900 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 19:20:28.903 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 19:20:28.905 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 19:20:28.907 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 19:20:28.907 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 19:20:28.916 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 19:20:28.916 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 19:20:28.920 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 19:20:28.920 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 19:20:29.118 [warning] <0.32.0> lager_error_logger_h dropped 58 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-06 19:21:07.449 [error] <0.299.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.304.0> exit with reason normal in context child_terminated
2018-07-06 19:21:07.493 [info] <0.33.0> Application lager started on node nonode@nohost
2018-07-06 19:21:07.501 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-07-06 19:21:07.505 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-07-06 19:21:07.507 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-06 19:21:07.509 [info] <0.33.0> Application recon started on node nonode@nohost
2018-07-06 19:21:07.509 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-07-06 19:21:07.519 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-07-06 19:21:07.519 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-07-06 19:21:07.521 [info] <0.33.0> Application agala started on node nonode@nohost
2018-07-06 19:21:07.521 [info] <0.33.0> Application agala_fb started on node nonode@nohost
2018-07-06 19:21:08.111 [warning] <0.32.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
